#
# File: makefile.def
# Create Time: Mon Jul 17 15:35:36 HKT 2006
# Author: jacowu
# Describe: 
#

#------------------------------------------------------------------------------
PROJ_ROOT =/home/jacowu/proj/tcpd
#------------------------------------------------------------------------------
# include
INC             = -I./
#------------------------------------------------------------------------------
# lib

LIB             = 
#------------------------------------------------------------------------------

C_FLAGS        = -g  -DDEBUG -Wall 
#C_FLAGS = -mcpu=pentiumpro -O3 -fomit-frame-pointer -Wall 
LD_FLAGS        =
CXX             = g++ 
AR              = ar
